name: Build Keil2Json Executable

on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
        python-version:
          - "3.9"
        include:
          - os: windows-latest
            script-ext: ".exe"
            pyinstaller-args: "--uac-admin"
          - os: ubuntu-latest
            script-ext: ""
            pyinstaller-args: ""

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Create virtual environment and install dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install pyinstaller

      - name: Create virtual environment and install dependencies (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          python -m venv venv
          venv\Scripts\activate
          pip install pyinstaller
        shell: powershell

      - name: Build Keil2Json executable
        if: matrix.os == 'ubuntu-latest'
        run: |
          source venv/bin/activate
          pyinstaller -F ${{ matrix.pyinstaller-args }} --distpath dist Keil2Json.py
        shell: bash

      - name: Build Keil2Json executable (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          venv\Scripts\activate
          pyinstaller -F ${{ matrix.pyinstaller-args }} --distpath dist Keil2Json.py
        shell: powershell

      - name: Zip executable
        if: matrix.os == 'ubuntu-latest'
        run: |
          mkdir -p output
          cp dist/Keil2Json output/
          zip -r Keil2Json-ubuntu-latest.zip output/
        shell: bash

      - name: Zip executable (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          mkdir output
          copy dist\Keil2Json.exe output\
          powershell Compress-Archive -Path output\* -DestinationPath Keil2Json-windows-latest.zip
        shell: powershell

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Keil2Json-${{ matrix.os }}
          path: Keil2Json-${{ matrix.os }}.zip

  release:
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Merge artifacts into output directory
        run: |
          mkdir -p output
          for dir in artifacts/*/; do
            platform=$(basename "$dir")
            mkdir -p "output/$platform"
            find "$dir" -name "*.zip" -exec unzip {} -d "output/$platform" \;
          done

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: output/**/*
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
